version: '3.8'
services:
  api-services:
    build: ./api-services
    ports:
      - "5000:5000"
  ui-services:
    build: ./ui-services
    ports:
      - "8016:80"
    depends_on:
      - api-services